[platformio]
default_envs = driveunit

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
board_build.filesystem = littlefs
board_build.filesystem_size = 0.1m ; ADJUST WHEN PROFILING OF NEEDED MEMORY DONE ELEPHANT

build_unflags =
    -std=gnu++17

build_flags =
    -w
    -std=gnu++20
    -DEIGEN_MPL2_ONLY           ; Use only modern C++ metaprogramming (fixes `result_of<>` issues)
    -DEIGEN_NO_MALLOC           ; Prevent Eigen from using dynamic memory (malloc/free)
    -DEIGEN_DONT_PARALLELIZE    ; Disable multi-threading (not needed on embedded)

    -DconfigCHECK_FOR_STACK_OVERFLOW=2
    -DconfigUSE_MALLOC_FAILED_HOOK=1
    -DconfigUSE_TRACE_FACILITY=1
    -DconfigGENERATE_RUN_TIME_STATS=1
    -DconfigUSE_STATS_FORMATTING_FUNCTIONS=1
    -DconfigUSE_IDLE_HOOK=1
    -DconfigUSE_TICK_HOOK=1
    -DconfigENABLE_FPU=1
    -DconfigUSE_TIME_SLICING=1

build_src_filter =
	+<*.h>
	-<.git/>
	-<.svn/>
    +<driveunit/*.cpp>

extra_scripts = pre:extra_script.py
monitor_speed = 115200

; Optional settings for additional libraries or configurations
lib_deps =
    ; Example library dependencies
    ; <Library name> == <Library version>
    ; Thirdparty libraries
    symlink://../thirdparty/zpp_bits
    symlink://../thirdparty/eigen
    symlink://../thirdparty/arduino_plotter
    stm32duino/STM32duino LSM6DSO@^2.2.0
    arduino-libraries/Madgwick@^1.2.0

    ; Project Libraries
    symlink://../common/utilities
    symlink://../driveunit_interface


[env:construction_check]
build_src_filter = ${env.build_src_filter} +<main_construction_check.cpp>

[env:driveunit]
build_src_filter = ${env.build_src_filter} +<main_driveunit.cpp>

[env:imu]
build_src_filter = ${env.build_src_filter} +<main_imu.cpp>

[env:imu_calibration]
build_src_filter = ${env.build_src_filter} +<main_imu_calibration.cpp>

[env:imu_kinematic]
build_src_filter = ${env.build_src_filter} +<main_imu_kinematic.cpp>

[env:imu_pid]
build_src_filter = ${env.build_src_filter} +<main_imu_pid.cpp>