[platformio]
default_envs = driveunit

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

build_unflags =
    -std=gnu++17

build_flags =
    -std=gnu++20
    -DEIGEN_MPL2_ONLY           ; Use only modern C++ metaprogramming (fixes `result_of<>` issues)
    -DEIGEN_NO_MALLOC           ; Prevent Eigen from using dynamic memory (malloc/free)
    -DEIGEN_DONT_PARALLELIZE    ; Disable multi-threading (not needed on embedded)

build_src_filter =
	+<*.h>
	-<.git/>
	-<.svn/>
	+<shared/>
	+<${PIOENV}/>
	+<main_${PIOENV}.cpp>
    +<driveunit/*.cpp>

extra_scripts = pre:extra_script.py
monitor_speed = 115200

; Optional settings for additional libraries or configurations
lib_deps =
    ; Example library dependencies
    ; <Library name> == <Library version>
    ; Thirdparty libraries
    symlink://../thirdparty/zpp_bits
    symlink://../thirdparty/eigen
    stm32duino/STM32duino LSM6DSO@^2.2.0
    arduino-libraries/Madgwick@^1.2.0

    ; Project Libraries
    symlink://../common/utilities
    symlink://../driveunit_interface


[env:construction_check]
[env:driveunit]
