[platformio]
default_envs = pico

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
extra_scripts = pre:extra_script.py
monitor_speed = 115200

; Optional settings for additional libraries or configurations
lib_deps =
    ; Example library dependencies
    ; <Library name> == <Library version>
    Wire
    Servo
